apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-ssd-storage
provisioner: docker.io/hostpath

---

# Expose es and kibana with host ports for easier access in docker-for-mac
apiVersion: v1
kind: Service
metadata:
  name: kibana-lb
  namespace: logs
  labels:
    app: kibana
spec:
  type: LoadBalancer
  ports:
    - port: 5601
      name: http
  selector:
    app: kibana

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-lb
  namespace: logs
  labels:
    app: elasticsearch
spec:
  type: LoadBalancer
  ports:
    - port: 9200
      name: http
  selector:
    app: elasticsearch
